import type {
  AppNotification,
  Community,
  ImpactEvent,
  Opportunity,
  Organization,
  Person,
  Recommendation,
  SupportRequest,
} from "./types";

export const communities: Community[] = [
  {
    id: "cocis",
    name: "College of Computing and Information Sciences",
    short: "CoCIS",
    kind: "college",
    tagline: "Makerere's computing, IT and information science community.",
    members: 1420,
    studentsHelped: 46,
    mentorshipSessions: 88,
    opportunitiesCreated: 34,
    resourcesShared: 27,
    accent: "primary",
  },
  {
    id: "cedat",
    name: "College of Engineering, Design, Art and Technology",
    short: "CEDAT",
    kind: "college",
    tagline: "Engineers, designers and builders supporting their own.",
    members: 1180,
    studentsHelped: 28,
    mentorshipSessions: 61,
    opportunitiesCreated: 22,
    resourcesShared: 19,
    accent: "connection",
  },
  {
    id: "chuss",
    name: "College of Humanities and Social Sciences",
    short: "CHUSS",
    kind: "college",
    tagline: "Humanities students, researchers and alumni.",
    members: 1610,
    studentsHelped: 21,
    mentorshipSessions: 40,
    opportunitiesCreated: 14,
    resourcesShared: 9,
    accent: "cyan",
  },
  {
    id: "caes",
    name: "College of Agricultural and Environmental Sciences",
    short: "CAES",
    kind: "college",
    tagline: "Agriculture, food systems and environment.",
    members: 970,
    studentsHelped: 17,
    mentorshipSessions: 26,
    opportunitiesCreated: 11,
    resourcesShared: 12,
    accent: "success",
  },
  {
    id: "conas",
    name: "College of Natural Sciences",
    short: "CONAS",
    kind: "college",
    tagline: "Mathematics, physics, chemistry and biology.",
    members: 840,
    studentsHelped: 13,
    mentorshipSessions: 18,
    opportunitiesCreated: 8,
    resourcesShared: 6,
    accent: "primary",
  },
  {
    id: "cs",
    name: "Computer Science (Makerere)",
    short: "Computer Science",
    kind: "course",
    tagline: "Everyone on the BSc Computer Science programme, past and present.",
    members: 520,
    studentsHelped: 31,
    mentorshipSessions: 74,
    opportunitiesCreated: 29,
    resourcesShared: 21,
    accent: "connection",
  },
  {
    id: "busia-alumni",
    name: "Busia Secondary School Alumni",
    short: "Busia SS Alumni",
    kind: "school-alumni",
    tagline: "From Busia to campus — and back again.",
    members: 214,
    studentsHelped: 12,
    mentorshipSessions: 23,
    opportunitiesCreated: 7,
    resourcesShared: 10,
    accent: "cyan",
  },
  {
    id: "mak-alumni",
    name: "Makerere Alumni Network",
    short: "Mak Alumni",
    kind: "organization",
    tagline: "Graduates giving structured support back to campus.",
    members: 3120,
    studentsHelped: 58,
    mentorshipSessions: 132,
    opportunitiesCreated: 47,
    resourcesShared: 33,
    accent: "success",
  },
];

export const CURRENT_USER_ID = "p-kizito";

export const people: Person[] = [
  {
    id: CURRENT_USER_ID,
    name: "Kizito Fahad",
    role: "student",
    headline: "Computer Science, Year 2 — CoCIS",
    college: "CoCIS",
    course: "Computer Science",
    year: 2,
    secondarySchool: "Busia Secondary School",
    communities: ["cocis", "cs", "busia-alumni"],
    skills: ["React", "Python", "Data structures", "Community organising"],
    offers: ["mentorship", "referral", "amplification"],
    verified: true,
    trustScore: 88,
    bio: "Second-year Computer Science student who runs a weekend coding club for first-years.",
  },
  {
    id: "p-amina",
    name: "Amina N.",
    role: "student",
    headline: "Computer Science, Year 2 — CoCIS",
    college: "CoCIS",
    course: "Computer Science",
    year: 2,
    secondarySchool: "Tororo Girls School",
    communities: ["cocis", "cs"],
    skills: ["Java", "Databases"],
    offers: ["amplification"],
    verified: true,
    trustScore: 91,
    bio: "Works part-time at a campus print shop while completing her second year.",
  },
  {
    id: "p-david",
    name: "David K.",
    role: "student",
    headline: "Civil Engineering, Year 3 — CEDAT",
    college: "CEDAT",
    course: "Civil Engineering",
    year: 3,
    secondarySchool: "Busia Secondary School",
    communities: ["cedat", "busia-alumni"],
    skills: ["AutoCAD", "Surveying"],
    offers: ["referral"],
    verified: true,
    trustScore: 84,
    bio: "Third-year engineering student from Busia, active in the district students' association.",
  },
  {
    id: "p-sarah",
    name: "Sarah M.",
    role: "mentor",
    headline: "Software Engineer — CoCIS alumna (2019)",
    college: "CoCIS",
    course: "Computer Science",
    secondarySchool: "Gayaza High School",
    communities: ["cocis", "cs", "mak-alumni"],
    skills: ["Backend engineering", "Career coaching"],
    offers: ["mentorship", "opportunity", "referral"],
    verified: true,
    trustScore: 95,
    bio: "Mentors two students each semester on backend engineering and interview prep.",
  },
  {
    id: "p-brian",
    name: "Brian O.",
    role: "alumni",
    headline: "Product Manager — Mak Alumni Network",
    college: "COBAMS",
    course: "Business Computing",
    secondarySchool: "Busia Secondary School",
    communities: ["mak-alumni", "busia-alumni"],
    skills: ["Product", "Fundraising"],
    offers: ["financial", "opportunity", "mentorship"],
    verified: true,
    trustScore: 93,
    bio: "Coordinates the Busia alumni tuition circle.",
  },
  {
    id: "p-grace",
    name: "Grace A.",
    role: "student",
    headline: "Pharmacy, Year 4 — CHS",
    college: "CHS",
    course: "Pharmacy",
    year: 4,
    secondarySchool: "Mbarara High School",
    communities: ["conas"],
    skills: ["Lab research"],
    offers: ["mentorship"],
    verified: true,
    trustScore: 87,
    bio: "Final-year pharmacy student and peer tutor in chemistry.",
  },
  {
    id: "p-joel",
    name: "Joel T.",
    role: "student",
    headline: "Software Engineering, Year 1 — CoCIS",
    college: "CoCIS",
    course: "Software Engineering",
    year: 1,
    secondarySchool: "Busia Secondary School",
    communities: ["cocis", "busia-alumni"],
    skills: ["JavaScript"],
    offers: [],
    verified: false,
    trustScore: 62,
    bio: "First-year student adjusting to campus life, looking for a study group.",
  },
  {
    id: "p-mercy",
    name: "Mercy W.",
    role: "student",
    headline: "Architecture, Year 3 — CEDAT",
    college: "CEDAT",
    course: "Architecture",
    year: 3,
    secondarySchool: "Nabisunsa Girls School",
    communities: ["cedat"],
    skills: ["Design", "3D modelling"],
    offers: ["resource"],
    verified: true,
    trustScore: 80,
    bio: "Runs the CEDAT model-making workshop share scheme.",
  },
  {
    id: "p-peter",
    name: "Peter M.",
    role: "supporter",
    headline: "Data Analyst — CoCIS alumnus (2017)",
    college: "CoCIS",
    course: "Computer Science",
    secondarySchool: "Namilyango College",
    communities: ["cocis", "cs", "mak-alumni"],
    skills: ["Analytics", "SQL"],
    offers: ["financial", "mentorship"],
    verified: true,
    trustScore: 92,
    bio: "Supports one tuition request per semester and mentors data-science beginners.",
  },
  {
    id: "p-esther",
    name: "Esther K.",
    role: "student",
    headline: "Social Work, Year 2 — CHUSS",
    college: "CHUSS",
    course: "Social Work",
    year: 2,
    secondarySchool: "Tororo Girls School",
    communities: ["chuss"],
    skills: ["Counselling", "Community work"],
    offers: ["amplification"],
    verified: true,
    trustScore: 78,
    bio: "Volunteers with a student welfare desk.",
  },
  {
    id: "p-ian",
    name: "Ian S.",
    role: "student",
    headline: "Statistics, Year 3 — CONAS",
    college: "CONAS",
    course: "Statistics",
    year: 3,
    secondarySchool: "Ntare School",
    communities: ["conas", "cs"],
    skills: ["R", "Statistics"],
    offers: ["mentorship"],
    verified: true,
    trustScore: 83,
    bio: "Tutors first-years in probability.",
  },
  {
    id: "p-fatuma",
    name: "Fatuma B.",
    role: "student",
    headline: "Agribusiness, Year 2 — CAES",
    college: "CAES",
    course: "Agribusiness",
    year: 2,
    secondarySchool: "Busia Secondary School",
    communities: ["caes", "busia-alumni"],
    skills: ["Field research"],
    offers: [],
    verified: true,
    trustScore: 76,
    bio: "Studying smallholder value chains in eastern Uganda.",
  },
  {
    id: "p-tony",
    name: "Tony R.",
    role: "mentor",
    headline: "Structural Engineer — CEDAT alumnus (2015)",
    college: "CEDAT",
    course: "Civil Engineering",
    secondarySchool: "Kings College Budo",
    communities: ["cedat", "mak-alumni"],
    skills: ["Structures", "Site supervision"],
    offers: ["mentorship", "opportunity"],
    verified: true,
    trustScore: 90,
    bio: "Hosts two site-visit days for CEDAT students each semester.",
  },
  {
    id: "p-lydia",
    name: "Lydia N.",
    role: "mentor",
    headline: "UX Designer — CoCIS alumna (2020)",
    college: "CoCIS",
    course: "Information Systems",
    secondarySchool: "Gayaza High School",
    communities: ["cocis", "mak-alumni"],
    skills: ["UX", "Portfolio reviews"],
    offers: ["mentorship", "resource"],
    verified: true,
    trustScore: 89,
    bio: "Reviews student portfolios every second Saturday.",
  },
  {
    id: "p-samuel",
    name: "Samuel O.",
    role: "student",
    headline: "Education, Year 4 — CEES",
    college: "CEES",
    course: "Education",
    year: 4,
    secondarySchool: "Jinja College",
    communities: ["cees" as unknown as string],
    skills: ["Teaching"],
    offers: ["mentorship"],
    verified: false,
    trustScore: 58,
    bio: "Trainee teacher on school practice in Jinja.",
  },
  {
    id: "p-ruth",
    name: "Ruth A.",
    role: "student",
    headline: "Economics, Year 1 — COBAMS",
    college: "COBAMS",
    course: "Economics",
    year: 1,
    secondarySchool: "Tororo Girls School",
    communities: ["cs"],
    skills: ["Excel", "Debate"],
    offers: [],
    verified: true,
    trustScore: 71,
    bio: "First-year economics student and campus debater.",
  },
  {
    id: "p-hassan",
    name: "Hassan L.",
    role: "student",
    headline: "Computer Science, Year 3 — CoCIS",
    college: "CoCIS",
    course: "Computer Science",
    year: 3,
    secondarySchool: "Busia Secondary School",
    communities: ["cocis", "cs", "busia-alumni"],
    skills: ["Android", "Kotlin"],
    offers: ["mentorship", "amplification"],
    verified: true,
    trustScore: 86,
    bio: "Builds Android apps for campus clubs.",
  },
  {
    id: "p-noeline",
    name: "Noeline K.",
    role: "supporter",
    headline: "Programme Officer — education non-profit",
    communities: ["mak-alumni"],
    skills: ["Grants", "Programme design"],
    offers: ["financial", "opportunity"],
    verified: true,
    trustScore: 94,
    bio: "Runs a small laptop-lending scheme for computing students.",
  },
  {
    id: "p-collins",
    name: "Collins B.",
    role: "student",
    headline: "Electrical Engineering, Year 2 — CEDAT",
    college: "CEDAT",
    course: "Electrical Engineering",
    year: 2,
    secondarySchool: "Ntare School",
    communities: ["cedat"],
    skills: ["Embedded systems"],
    offers: ["resource"],
    verified: true,
    trustScore: 79,
    bio: "Repairs and refurbishes donated laptops for classmates.",
  },
  {
    id: "p-diana",
    name: "Diana M.",
    role: "student",
    headline: "Journalism, Year 3 — CHUSS",
    college: "CHUSS",
    course: "Journalism",
    year: 3,
    secondarySchool: "Nabisunsa Girls School",
    communities: ["chuss"],
    skills: ["Writing", "Photography"],
    offers: ["amplification"],
    verified: true,
    trustScore: 81,
    bio: "Documents student impact stories for campus media.",
  },
];

export const peopleById = Object.fromEntries(people.map((p) => [p.id, p]));
export const communitiesById = Object.fromEntries(communities.map((c) => [c.id, c]));

export const supportRequests: SupportRequest[] = [
  {
    id: "r-amina-tuition",
    personId: "p-amina",
    title: "UGX 350,000 remaining tuition balance",
    category: "Tuition",
    need: "UGX 350,000 to clear the semester tuition balance before exam registration closes.",
    why: "My family covered most of the semester, but a delayed harvest payment left a balance. Without clearing it I cannot sit end-of-semester exams.",
    amountNeeded: 350000,
    amountRaised: 210000,
    deadlineDays: 14,
    supporters: 6,
    supportTypes: ["financial", "mentorship", "amplification", "referral"],
    status: "verified",
    checks: { identity: true, studentStatus: true, documents: true, humanReview: true },
    createdAt: "2026-08-14",
  },
  {
    id: "r-joel-laptop",
    personId: "p-joel",
    title: "A working laptop for first-year programming",
    category: "Laptop / Equipment",
    need: "A refurbished laptop (or a loan of one) for coursework and lab practicals.",
    why: "I share a lab machine with three classmates and can only code during limited lab hours, which is affecting my practicals.",
    resourceNeeded: "Refurbished laptop, 8GB RAM",
    amountNeeded: 900000,
    amountRaised: 150000,
    deadlineDays: 21,
    supporters: 3,
    supportTypes: ["resource", "financial", "mentorship", "amplification"],
    status: "pending",
    checks: { identity: true, studentStatus: true, documents: false, humanReview: false },
    createdAt: "2026-08-28",
  },
  {
    id: "r-esther-accom",
    personId: "p-esther",
    title: "One month of hostel accommodation",
    category: "Accommodation",
    need: "UGX 280,000 for one month of hostel rent while a bursary is processed.",
    why: "My bursary disbursement was pushed to next month and I am commuting three hours a day in the meantime.",
    amountNeeded: 280000,
    amountRaised: 95000,
    deadlineDays: 9,
    supporters: 4,
    supportTypes: ["financial", "amplification", "referral"],
    status: "verified",
    checks: { identity: true, studentStatus: true, documents: true, humanReview: true },
    createdAt: "2026-08-22",
  },
  {
    id: "r-fatuma-mentor",
    personId: "p-fatuma",
    title: "Mentorship for an agribusiness research project",
    category: "Mentorship",
    need: "A mentor working in agricultural value chains to review my research design.",
    why: "My project on smallholder maize pricing needs guidance from someone with field experience.",
    deadlineDays: 30,
    supporters: 2,
    supportTypes: ["mentorship", "opportunity", "referral", "amplification"],
    status: "verified",
    checks: { identity: true, studentStatus: true, documents: true, humanReview: true },
    createdAt: "2026-08-19",
  },
  {
    id: "r-collins-intern",
    personId: "p-collins",
    title: "Industrial training placement for recess term",
    category: "Career / Internship",
    need: "An industrial training placement in electrical installation or power systems.",
    why: "Recess-term industrial training is compulsory and placements near campus fill up quickly.",
    deadlineDays: 25,
    supporters: 1,
    supportTypes: ["opportunity", "referral", "mentorship", "amplification"],
    status: "needs-info",
    checks: { identity: true, studentStatus: true, documents: false, humanReview: false },
    createdAt: "2026-09-01",
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "o-1",
    title: "Backend Engineering Internship",
    org: "Kampala fintech (fictional)",
    kind: "Internship",
    location: "Kampala — hybrid",
    closesInDays: 12,
    summary: "Three-month paid internship building payment APIs alongside a senior engineer.",
    matchReason: "Matched because you study Computer Science.",
    communities: ["cs", "cocis"],
  },
  {
    id: "o-2",
    title: "CoCIS Women & Allies in Tech Scholarship",
    org: "Makerere Alumni Network",
    kind: "Scholarship",
    location: "Makerere University",
    closesInDays: 20,
    summary: "Partial tuition scholarship for continuing computing students with strong coursework.",
    matchReason: "Matched because you belong to CoCIS.",
    communities: ["cocis"],
  },
  {
    id: "o-3",
    title: "Alumni Mentorship Cohort — Semester 1",
    org: "Mak Alumni Network",
    kind: "Mentorship",
    location: "Online, fortnightly",
    closesInDays: 8,
    summary: "Six sessions with an alumnus working in your field, plus a portfolio review.",
    matchReason: "Matched because three mentors in your communities are accepting students.",
    communities: ["mak-alumni", "cocis"],
  },
  {
    id: "o-4",
    title: "East Africa Student Hackathon",
    org: "Regional student tech network (fictional)",
    kind: "Hackathon",
    location: "Kampala — 48 hours",
    closesInDays: 15,
    summary: "Team hackathon on civic technology; travel stipend for upcountry students.",
    matchReason: "Matched because your skills include React and Python.",
    communities: ["cs", "cedat"],
  },
  {
    id: "o-5",
    title: "Part-time Campus Data Assistant",
    org: "University research group (fictional)",
    kind: "Part-time",
    location: "On campus — 10 hrs/week",
    closesInDays: 6,
    summary: "Flexible paid work cleaning and visualising survey data for a research team.",
    matchReason: "Matched because you are in Year 2 and listed data skills.",
    communities: ["cocis", "conas"],
  },
];

export const organizations: Organization[] = [
  {
    id: "org-mak-alumni",
    name: "Makerere Alumni Network",
    kind: "Alumni organization",
    studentsReached: 412,
    campaigns: 6,
    mentorshipSessions: 132,
    opportunitiesCreated: 47,
    blurb: "Coordinates alumni giving, mentorship cohorts and opportunity pipelines back into campus.",
  },
  {
    id: "org-laptop-fund",
    name: "Eastern Uganda Laptop Fund",
    kind: "Non-profit",
    studentsReached: 96,
    campaigns: 3,
    mentorshipSessions: 12,
    opportunitiesCreated: 5,
    blurb: "Refurbishes and lends laptops to computing students from eastern Uganda.",
  },
  {
    id: "org-cedat-guild",
    name: "CEDAT Students' Guild",
    kind: "Student organization",
    studentsReached: 188,
    campaigns: 4,
    mentorshipSessions: 34,
    opportunitiesCreated: 16,
    blurb: "Runs emergency support and workshop-resource sharing for engineering students.",
  },
];

export const recommendations: Recommendation[] = [
  { personId: "p-amina", relevance: 92, reasons: ["Same college — CoCIS", "Same course — Computer Science", "Same community"] },
  { personId: "p-david", relevance: 81, reasons: ["Same secondary school — Busia SS", "Makerere alumni connection"] },
  { personId: "p-sarah", relevance: 76, reasons: ["Mentorship interest", "Same academic field"] },
  { personId: "p-hassan", relevance: 74, reasons: ["Same course — Computer Science", "Same secondary school"] },
  { personId: "p-lydia", relevance: 68, reasons: ["Offers portfolio mentorship", "Same college — CoCIS"] },
  { personId: "p-joel", relevance: 64, reasons: ["Same secondary school", "First-year in your college"] },
];

export const seedImpact: ImpactEvent[] = [
  { id: "i-1", date: "2026-08-21", type: "financial", label: "Supported a tuition request", detail: "Contributed to Amina N.'s tuition balance", privacy: "recognized" },
  { id: "i-2", date: "2026-08-17", type: "mentorship", label: "Mentored a Computer Science student", detail: "First session with Joel T.", privacy: "recognized" },
  { id: "i-3", date: "2026-08-12", type: "opportunity", label: "Referred an internship opportunity", detail: "Shared a backend internship with the CS community", privacy: "public" },
  { id: "i-4", date: "2026-08-04", type: "resource", label: "Lent a resource", detail: "Loaned a laptop charger set to CEDAT workshop share", privacy: "private" },
  { id: "i-5", date: "2026-07-29", type: "amplification", label: "Amplified a request", detail: "Shared Esther K.'s accommodation request with Busia SS Alumni", privacy: "public" },
];

export const seedNotifications: AppNotification[] = [
  { id: "n-1", title: "New mentorship match", body: "Sarah M. is accepting one more mentee in backend engineering.", at: "2h ago", read: false, tone: "match" },
  { id: "n-2", title: "Someone from your community needs support", body: "Amina N. (CoCIS, Computer Science) has a verified tuition request.", at: "5h ago", read: false, tone: "support" },
  { id: "n-3", title: "New opportunity matched to your profile", body: "Backend Engineering Internship closes in 12 days.", at: "Yesterday", read: false, tone: "opportunity" },
  { id: "n-4", title: "Your student status was verified", body: "Your Makerere student status check passed human review.", at: "2 days ago", read: true, tone: "verification" },
  { id: "n-5", title: "Your Impact Passport was updated", body: "A mentorship connection was added to your passport.", at: "3 days ago", read: true, tone: "impact" },
];

export const communityActivity = [
  { id: "ca-1", community: "cocis", label: "Laptop support delivered", detail: "CoCIS Laptop Support campaign reached 14 of 20 students", when: "2 days ago" },
  { id: "ca-2", community: "cs", label: "Mentorship session", detail: "8 sessions logged this month by Computer Science mentors", when: "4 days ago" },
  { id: "ca-3", community: "busia-alumni", label: "Tuition circle", detail: "Busia SS Alumni cleared 2 tuition balances this semester", when: "1 week ago" },
  { id: "ca-4", community: "cedat", label: "Internship referral", detail: "CEDAT alumni referred 5 students for industrial training", when: "1 week ago" },
];

export const campaign = {
  name: "CoCIS Laptop Support",
  goalStudents: 20,
  supportedStudents: 14,
  laptops: 11,
  tablets: 3,
  mentorshipSessions: 8,
};

export function ugx(n: number) {
  return `UGX ${n.toLocaleString("en-UG")}`;
}
